### ISSUE TITLE
Container restarting immediately after creation

### ISSUE THREAD

**Issue by Grandma-Betty** [vdsm/virtual-dsm#208]
From docker image version 3.98 on upwards, the container restarts immediately after being created.
Jumping back to container version 3.97 of your image, it works fine again.

![Unbenannt](https://github.com/kroese/virtual-dsm/assets/48346793/d82d9f5b-078f-42cc-b3c0-e44673192f8c)

```
version: "3"
services:
    dsm:
        container_name: vdsm01
        image: kroese/virtual-dsm:latest
        environment:
            DISK_SIZE: "128G"
            RAM_SIZE: "8192M"
            CPU_CORES: "2"
            HOST_SERIAL: "xxxxxxxxxx"
            GUEST_SERIAL: "xxxxxxxxxx"
            VM_NET_MAC: "xx:xx:xx:xx:xx:xx"
            ALLOCATE: "N"
        devices:
            - /dev/kvm
        volumes:
            - /home/admin/vDSM01/storage:/storage
        cap_add:
            - NET_ADMIN
        ports:
            - "5000:5000"
            - "5001:5001"
        restart: unless-stopped
        stop_grace_period: 60s
```
Anything else I can provide to troubleshoot?
Thanks!
