### ISSUE TITLE
MacVLAN and vDSM IP Address

### ISSUE THREAD

**Issue by coolspot18** [vdsm/virtual-dsm#296]
Hi kroese,

Great project, vDSM is up and running with MacVLAN, however, vDSM is still showing an IP address of 20.20.20.21. 

I can reach vDSM using the IP address I configured with MacVLAN (192.168.1.110), but DSM itself still thinks it's 20.20.20.21. While DSM works, the internal IP address is causing some issues with Synology Directory Server since it registers itself to DNS.

Is there a way to set DSM's network IP address to 192.168.1.110 to match the MacVLAN configuration?

```docker network create -d macvlan \
    --subnet=192.168.1.0/23 \
    --gateway=192.168.1.1 \
    --ip-range=192.168.1.110/32 \
    -o parent=enp6s18 vdsm
```

**Comment by coolspot18** [comment]
I tried DHCP, and the container is picking a dynamic IP address, however, the web interface keeps looping with the following screen.

![image](https://github.com/kroese/virtual-dsm/assets/5160442/b12b3d74-47e9-4553-ab94-853102229132)

Secondly, Synology Directory Server needs a static IP address, at least to set it up initially.

**Comment by coolspot18** [comment]
Thank for the details - one last Q, not related to virtual DSM, but does the container IP address have to be within the subnet IP range of the MacVLAN? Interesting how docker can allow you to set the container IP address outside of the assigned MacVLAN network and it still works... is that because DHCP uses macvtap and it ignores the IP range?

**Comment by inuites** [comment]
Hi everyone, 
I've set up my vDSM with a MacVLAN network. It's working fine; the vDSM has its own IP address (192.168.1.241), and I can manually access the shares in Windows by entering the share path, for example, \\192.168.1.241\share1. Unfortunately, SMB discovery isn't working, even though WS-Discovery is activated in the DSM configuration panel. Is there anything else I need to do to resolve this issue?

macVLAN settings
```
docker network create -d macvlan \
    --subnet=192.168.1.0/24 \
    --gateway=192.168.1.1 \
    --ip-range=192.168.1.240/28 \
    -o parent=enp6s18 vdsm
```

docker-compose.yml: 
```
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
        RAM_SIZE: "8G"
        CPU_CORES: "4"
        DISK_SIZE: "16G" # system disk
        ALLOCATE: "N" # growable disk
        DISK_FMT: "qcow2" # growable disk
        DEVICE2: "/dev/vdb" # data disk
        DHCP: "Y"
    devices:
        - /dev/kvm
        - /dev/vdb #passthrough proxmox virtual disk to docker
        - /dev/vhost-net
    networks:
      vdsm:
        ipv4_address: 192.168.1.240
    device_cgroup_rules:
        - 'c *:* rwm'
    cap_add:
        - NET_ADMIN
    volumes:
        - /var/dsm:/storage # location of local DSM
    restart: unless-stopped
    stop_grace_period: 1m

networks:
  vdsm:
    external: true
```
