### ISSUE TITLE
ERROR: Not enough free space for installation, need at least 6 GB.

### ISSUE THREAD

**Issue by AcosX** [vdsm/virtual-dsm#417]
I'm using Docker on Windows to install.This is my docker-compose.yml:
```
version: "3"
name: dsm
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm:latest
    environment:
      DISK_SIZE: "512G"
      ALLOCATE: "N"
      DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      - /mnt/host/d/dsm:/storage
    restart: on-failure
    stop_grace_period: 1m
    networks:
      vdsm:
        ipv4_address: 192.168.2.100
networks:
  vdsm:
    external: true
```
and when I run the container,It noticed in log as follow:
```
2023-12-02 14:54:05 dsm  | ❯ Starting Virtual DSM for Docker v4.36...
2023-12-02 14:54:05 dsm  | ❯ For support visit https://github.com/vdsm/virtual-dsm/
2023-12-02 14:54:05 dsm  | ❯ ERROR: Not enough free space for installation, need at least 6 GB.
```
But there's still a lot of spaces on the disk.
