### ISSUE TITLE
curl: (6) Could not resolve host: global.synologydownload.com

### ISSUE THREAD

**Issue by geekyouth** [vdsm/virtual-dsm#478]
```
cat .env
PARENT_NETCARD: ens33
DEFAULT_GATEWAY_PREFIX: 192.168.3

```

```yaml
version: "3.9"

services:
  dsm:
    image: vdsm/virtual-dsm:5.05
    hostname: dsm
    container_name: dsm-dev
    networks:
      dsm_net:
    environment:
      TZ: Asia/Shanghai
      # 仅分配实际使用空间的可增长磁盘
      ALLOCATE: "N"
      DISK_FMT: "qcow2"
      # 多个磁盘
      DISK_SIZE: "50G" # 第一个名字是默认的，对应 /storage
      DISK2_SIZE: "50G"
      DISK3_SIZE: "50G"
      # 修改配置，默认分配单核和 1 GB RAM
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      # 手动修改静态 IP
      DHCP: "Y"
      # GPU 支持
      GPU: "Y"
    devices:
      - /dev/kvm
      - /dev/vhost-net
      - /dev/dri
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    #ports:
      #- "5000:5000"
    volumes:
      # 多个磁盘
      - /data/dsm-dev/storage/:/storage/
      - /data/dsm-dev/storage2/:/storage2/
      - /data/dsm-dev/storage3/:/storage3/
    restart: unless-stopped
    stop_grace_period: 2m
    dns:
      - 223.5.5.5
      - 4.2.2.2

networks:
  dsm_net:
    driver: macvlan
    attachable: true
    driver_opts:
      parent: ${PARENT_NETCARD}
    ipam:
      config:
        - subnet: ${DEFAULT_GATEWAY_PREFIX}.0/24
          gateway: ${DEFAULT_GATEWAY_PREFIX}.1


```

```
curl: (6) Could not resolve host: global.synologydownload.com
dsm-dev  | ❯ ERROR: Failed to download https://global.synologydownload.com/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat, reason: 6

```
![image](https://github.com/vdsm/virtual-dsm/assets/12899262/77447631-10e2-4e59-8085-d6609f12b46a)
