### ISSUE TITLE
Running vDSM in service network mode

### ISSUE THREAD

**Issue by pwntester** [vdsm/virtual-dsm#548]
Hi,

Im trying to run vDSM through a vpn container like:

```
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm:latest
    network_mode: "service:vpn"
    depends_on:
      - vpn
    environment:
      - DISK_SIZE=128G
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - ${CONFIG_ROOT}/dsm:/storage
    restart: on-failure
    stop_grace_period: 2m
  vpn:
    container_name: vpn
    image: ghcr.io/bubuntux/nordlynx
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    ports:
      - 5555:5000
      - 7777:7777
```

However, I cant reach the vDSM port. DSM seems to start ok:

```
[1;34m❯ [1;36m You can now login to DSM at http://169.254.116.106:5000[0m
```

But then after a minute or so it receives a SIGTERM and shuts itself down:

```
[1;34m❯ [1;36mReceived SIGTERM signal, sending shutdown command...[0m
```

When I configure vDSM to use the vpn container for its network, it also disables the access to other containers using the vpn (eg: the port 7777 is also not reachable)

Is it possible to run vDSM network through another container at all?
