### ISSUE TITLE
Error when first disk is a device

### ISSUE THREAD

**Issue by lars18th** [vdsm/virtual-dsm#549]
Hi,

I'm using this `docker-compose.yml`:
```
version: "3"
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm:latest
    environment:
      DEVICE: "/dev/sdc"
      DEVICE2: "/dev/sdd"
      DEVICE3: "/dev/sde"
    devices:
      - /dev/kvm
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      /var/dsm:/storage
    restart: on-failure
    stop_grace_period: 2m
```

But, then at initial install I get this message:
```
dsm  | ❯ ERROR: Not enough free space to create a disk of 16G in /storage, it has only 14 GB available...
dsm  | ❯ ERROR: Please specify a smaller DISK_SIZE or disable preallocation by setting ALLOCATE=N.
dsm exited with code 0
```

Because my "root" partition has only 14GB. What I need is to use the `/dev/sdc` as the disk for the FIRST disk.
Any idea to fix it?
Thank you.
