### ISSUE TITLE
Error with secondary and up devices

### ISSUE THREAD

**Issue by lars18th** [vdsm/virtual-dsm#550]
Hi @kroese ,

When using DEVICES only the first one works. When you connect DEVICE2 until DEVICE6, the qemu driver seems to have some trouble with the controller and prints this:
```
dsm  | [   13.230684] scsi host8: Virtio SCSI HBA
dsm  | [   13.390521] scsi 8:0:0:0: Direct-Access     QEMU     QEMU HARDDISK            2.5+ PQ: 0 ANSI: 5
dsm  | [   13.407881] want_idx 0 index 1. delay and reget
dsm  | [   14.413161] want_idx 0 index 1
dsm  | [   14.418849] want_idx 0 index 1. delay and reget
dsm  | [   15.422182] want_idx 0 index 1
[it repeats a lot of times]
```

And then the disk is not attached.

You can check it using _only one_ device. Change from this:
```
    environment:
      DEVICE: "/dev/sdc"
```
that will work, to this:
```
    environment:
      DEVICE2: "/dev/sdc"
```
And then you'll see the trouble (with DEVICE2 or DEVICE6 or anything else).

**Comment by lars18th** [comment]
> You could try replacing 0x5 by 0xd and see if it makes a difference? I cannot test this myself as I have no spare disk devices on my system.

I'll try it.

**Comment by lars18th** [comment]
Thank you @kroese . Very usefull information. I'll try to test then with the `scsi-id=` parameter and the virtual controllers.

**Comment by lars18th** [comment]
Hi @kroese ,

You are the master! It works like a charm! Tested with config:
```
[...]
    environment:
      DISK_SIZE: "6G"
      ALLOCATE: "N"
      DISK_FMT: "qcow2"
      DEVICE: "/dev/sda"
      DEVICE2: "/dev/sdb"
      DEVICE3: "/dev/sdc"
    devices:
      - /dev/kvm
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
    volumes:
      - /opt/virtual-dsm/storage:/storage
      - /opt/virtual-dsm/disk.sh:/run/disk.sh
[...]
```
And now the container starts without troubles and only the three devices are used. Congratulations!

I hope you'll merge it soon. I'll check with a new install without DISK_SIZE, ALLOCATE and DISK_FMT. The idea is to not create the initial disk image. Or almost create it empty with the minimum data and after don't use it at all.

😉
