### ISSUE TITLE
About HDD pass-through

### ISSUE THREAD

**Issue by yuantao313** [vdsm/virtual-dsm#651]
I pass-through a physical disk and virtual-dsm created a file system on it. Then if I move the disk to another Synology device or another virtual-dsm container, will the files in the disk be okay?
What I only know is that disks on physical Synology devices can be moved freely.

**Comment by yuantao313** [comment]
After testing, I found:

- If a disk were moved from a vDSM to a physical DSM, the physical DSM will let you confirm to format it.
- If a disk were moved from a physical DSM to a vDSM, the vDSM will not recognize the disk.
- It is avaliable to move the disks among only vDSMs or only physical DSMs.

These results can be added to the README.md in my opinion.

In fact,

- A vDSM only creates a btrfs part for the entire disk and mounts them to /volumex, which x is the disk number.
- But a physical DSM does not only create a data part, but also creates some extra parts to store DSM system files.

The results can be added to the README.md in my opinion.

**Comment by srctar** [comment]
> Sorry, I had misread your question. Because I already knew that the partition table is different between normal (physical) DSM and virtual DSM. For exactly the reason that you say: it contains not only data, but also partitions for the OS system files.
> 
> I thought you were asking about moving physical disks from one vDSM to another vDSM. If I had read your question better, it would have saved you a lot of work, sorry!

my vDSM is in a ubuntu server(physical)，  ubuntu is installed on a nvme device,  and also a sata device on it , names /dev/sda，
I passthrough the /dev/sda on the vDSM, I can see it on terminal， but I canot see it on “存储空间管理员”， is it correct?
looks like:
 
<img width="887" alt="QQ20240410-143159@2x" src="https://github.com/vdsm/virtual-dsm/assets/9291713/958ce2e1-e62f-4e18-a0f1-904e8050689f">

no ssd/hdd show here。

**Comment by srctar** [comment]
> Show your compose file or run command

here it is:
```
version: "3"
services:
  dsm:
    container_name: dsm-5001
    image: vdsm/virtual-dsm:latest
    environment:
      DEVICE2: "/dev/sda"
      DISK_SIZE: "120G"
      RAM_SIZE: "6G"
      DHCP: "Y"
      GPU: "Y"
      URL: "https://global.synologydownload.com/download/DSM/release/7.2.1/69057-1/DSM_VirtualDSM_69057.pat"
    devices:
      - /dev/sda
      - /dev/kvm
      - /dev/dri
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - /dsm:/storage
    restart: always
    stop_grace_period: 2m
```
