### ISSUE TITLE
How to create a storage pool?

### ISSUE THREAD

**Issue by pguitard** [vdsm/virtual-dsm#652]
I have 2 hard drives attached to my system and defined them both as pass-through in docker-compose:

```
environment:
  DEVICE: "/dev/sdb"
  DEVICE2: "/dev/sdc"
devices:
  - /dev/sdb
  - /dev/sdc
```

But after running the installation I get 2 volumes, one for each drive. How do I create a storage pool with the 2 drives in it?
