### ISSUE TITLE
How can I configure SMB shares in Virtual DSM?

### ISSUE THREAD

**Issue by Gunlance** [vdsm/virtual-dsm#667]
Accessing SMB shares within a Virtual DSM  running in a Docker container inside an unprivileged LXC container

Not a native English speaker, referenced other people’s code. 

https://github.com/vdsm/virtual-dsm/issues/382

```bash
# ls -l /dev-104/*
crw-rw---- 1 100000 messagebus 10, 232 Mar 28 23:40 /dev-104/kvm
crw-rw---- 1 100000 messagebus 10, 238 Mar 28 23:40 /dev-104/vhost-net

/dev-104/dri:
total 0
crw-r--r-- 1 100000 100000 226,   0 Mar 28 23:40 card0
crw-r--r-- 1 100000 100000 226, 128 Mar 28 23:40 renderD128

/dev-104/net:
total 0
crw-rw-rw- 1 100000 100000 10, 200 Mar 28 23:40 tun
```

my lxc.conf

```conf
# lxc.config
arch: amd64
cores: 4
features: fuse=1,mount=nfs;cifs,nesting=1
hostname: lxc-ubuntu
memory: 4096
mp0: /mnt/ssd1,mp=/mnt/ssd1
mp1: /mnt/ssd1/docker_runtime,mp=/var/lib/docker
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.1.3,hwaddr=xx:xx:xx:xx:xx:xx,ip=192.168.1.66/24,ip6=dhcp,type=veth
onboot: 1
ostype: ubuntu
rootfs: local:104/vm-104-disk-0.raw,mountoptions=lazytime,size=16G
startup: order=2
swap: 4096
lxc.apparmor.profile: unconfined
lxc.cgroup2.devices.allow: c 10:232 rwm
lxc.cgroup2.devices.allow: c 10:238 rwm
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.mount.entry: /dev-104/net/tun dev/net/tun none bind,create=file 0 0
lxc.mount.entry: /dev-104/kvm dev/kvm none bind,create=file 0 0
lxc.mount.entry: /dev-104/vhost-net dev/vhost-net none bind,create=file 0 0
lxc.mount.entry: /dev-104/dri/card0 dev/dri/card0 none bind,create=file 0 0
lxc.mount.entry: /dev-104/dri/renderD128 dev/dri/renderD128 none bind,create=file 0 0
```

my docker-compose.yml

```yaml
version: "3.8"
networks:
  #vdsm:
  #  driver: macvlan
  #  driver_opts:
  #    parent: eth0.83
  #  ipam:
  #    config:
  #      - subnet: 192.168.1.0/24
  #        gateway: 192.168.1.1
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      DISK1_SIZE: "16G"
      DISK2_SIZE: "64G"
    volumes:
      - ./dsm:/storage1
      - /mnt/ssd1/tmp:/storage2
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
      - /dev/dri
    device_cgroup_rules:
      - c *:* rwm
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
      - 445:445
    restart: unless-stopped
    stop_grace_period: 2m
    environment:
      DISK_FMT: "qcow2"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      GPU: "Y"
      ALLOCATE: "N"
      # DHCP: "Y"
    sysctls:
      - net.ipv4.ip_forward=1
    #networks:
    #  vdsm:
    #    ipv4_address: 192.168.1.100
```

The current issue is that accessing the DSM’s shared folders via SMB is not possible. [How can this be configured? Additionally, how can the network be configured to assign the DSM its own IP within the 192.168.1.0/24 subnet?

Thanks!
