### ISSUE TITLE
Error when adding "DHCP=Y" to docker-compose with macvlan network

### ISSUE THREAD

**Issue by BobWs** [vdsm/virtual-dsm#668]
Hi,

When I try to install vDSM with a macvlan network and as suggested adding `DHCP=Y` to the environment then I'm getting this error and the container won't finish the installation.
this is the error (with DEBUG=Y):
```
❯ Host: ddsm  IP: 192.168.178.125  Gateway: 192.168.178.1  Interface: eth0  MAC: 02:11:32:A6:0A:CF
nameserver 127.0.0.11
RTNETLINK answers: Operation not supported
❯ ERROR: Cannot create macvtap interface. Please make sure the network type is 'macvlan' and not 'ipvlan',
❯ ERROR: and that the NET_ADMIN capability has been added to the container: --cap-add NET_ADMIN
```
When I remove `DHCP=Y` then the installation goes well and I can create a user and login.

But then when I try to add a OpenVPN client connection in "Network/Network Interface/Create OpenVPN" The VPN Connection is created but it can not connect, it keeps hanging on connection.. and after a while I loose complete connection to the vDSM container and I can not login anymore, not even when I restart the container.

![Screen_Shot](https://github.com/vdsm/virtual-dsm/assets/5485820/d3985fd5-6b66-48ef-baf3-f40c3eb88e12)

This is my docker-compose file for installing vdsm on docker on a Synology NAS.
```
version: '3.8'

services:
  ddsm:              
    container_name: ddsm
    image: vdsm/virtual-dsm:latest
    hostname: ddsm
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    ports:
      - "5500:5000"
      - "5501:5001"
    volumes:
      - type: bind 
        source: /volume1/ddsm
        target: /storage
    environment:
      TZ: "Europe/Amsterdam"
      DISK_SIZE: "16G"
      DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'      
    networks:
      macvlan0:
        ipv4_address: 192.168.178.125
    restart: "on-failure"
    stop_grace_period: 2m    

networks:
  macvlan0:
    external: true
```
my macvlan network:
```
docker network create -d macvlan \
 --subnet=192.168.178.0/24 \
 --ip-range=192.168.178.125/24 \
 --gateway=192.168.178.1 \
 -o parent=ovs_eth0 \
 macvlan0
```
Any suggestions how to solve this?
Is it possible to use the builtin OpenVPN Client connection with your VDSM container?
TIA
