### ISSUE TITLE
Can't access vdsm when connected to wireguard vpn

### ISSUE THREAD

**Issue by Vandaahl** [vdsm/virtual-dsm#672]
I have virtual-dsm installed on Fedora server edition. I also have a [wg-easy](https://github.com/wg-easy/wg-easy) wireguard vpn set up as a docker container. And lastly I have a [traefik/whoami](https://github.com/traefik/whoami) container, running on port 81. These 3 docker containers run on the Fedora host with bridged networking.

On my phone I connect to the wireguard vpn and then I can open http://192.168.1.250:81 (the whoami container) just fine, but dsm keeps timing out at http://192.168.1.250:5000.

My docker-compose.yml:

```
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      DISK_SIZE: "16G"
      RAM_SIZE: "16G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
      - /dev/dri
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
      - 3322:22
    volumes:
      - /home/me/docker/virtual-dsm/dsm:/storage
    restart: unless-stopped
    stop_grace_period: 2m
```

I'm not sure if this is a virtual-dsm issue in the first place, but perhaps anyone faced the same issue?
