### ISSUE TITLE
[Question]: How can I use host or ipvlan?

### ISSUE THREAD

**Issue by COkedat** [vdsm/virtual-dsm#725]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/vdsm/virtual-dsm/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

I am currently trying to use ipvlan or host network mode so i can get real local ip from my router (iptime) and set firewall correctly

but there are some errors such as connection refused, unreachable

is it available to use ipvlan or host mode on virtual dsm?

Here is my docker-compose.yml
```
version: "3"
services:
    dsm:
        container_name: dsm
        image: vdsm/virtual-dsm:7.04
        environment:
            DISK_SIZE: "48G"
            RAM_SIZE: "2G"
            CPU_CORES: "2"
            URL: "https://global.synologydownload.com/download/DSM/release/7.2.1/69057-1/DSM_VirtualDSM_69057.pat"
            CONSOLE: "Y"
        devices:
            - /dev/kvm
        device_cgroup_rules:
            - 'c *:* rwm'
        cap_add:
            - NET_ADMIN
        ports:
            - 5000:5000
            - 5001:5001
            - 80:80
        volumes:
            - //c/docker_dsm:/storage
        networks:
            vdsm:
                ipv4_address: 192.168.0.120
        restart: always
        stop_grace_period: 2m
networks:
  vdsm:
    driver: ipvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.0/24```

**Comment by COkedat** [comment]
> Host or ipvlan are not supported, only bridge and macvlan.

If I use macvlan, the console shows wrong IP that is not fit with iptime's DHCP ip range (it starts with 192.168.0.100~)

```
version: "3"
services:
    dsm:
        container_name: dsm
        image: vdsm/virtual-dsm:7.04
        environment:
            DISK_SIZE: "48G"
            RAM_SIZE: "2G"
            CPU_CORES: "2"
            URL: "https://global.synologydownload.com/download/DSM/release/7.2.1/69057-1/DSM_VirtualDSM_69057.pat"
            CONSOLE: "Y"
            DHCP: "Y"
        devices:
            - /dev/kvm
            - /dev/vhost-net
        device_cgroup_rules:
            - 'c *:* rwm'
        cap_add:
            - NET_ADMIN
        ports:
            - 5000:5000
            - 5001:5001
            - 80:80
        volumes:
            - //c/docker_dsm:/storage
        networks:
            vdsm:
                ipv4_address: 192.168.0.120
        mac_address: 1C:69:74:09:72:E3
        restart: always
        stop_grace_period: 2m
networks:
  vdsm:
    external: true
```
with this message
```
dsm  | ❯ -----------------------------------------------------------
dsm  | ❯  You can now login to DSM at http://192.168.0.3:5000
dsm  | ❯ -----------------------------------------------------------
dsm  |
dsm  | [   55.929172] findhostd uses obsolete (PF_INET,SOCK_PACKET)
dsm  | [   59.761099] fuse init (API version 7.23)
```

Is there something wrong with what i have done?

**Comment by COkedat** [comment]
> Yes, many things look wrong..
> 
> Firstly: the container and the VM will both get their own IP if you set DHCP=Y, and they are completely seperated. But you are totally mixing them. You created a macvlan network that has the same range as the iptime, thats not good because it can give conflicts. Next you assign an address to the container (192.168.0.120) that is in your iptimes range. Dont do it.
> 
> Also you are setting a mac address for the container, I dont know why. But dont do that because DHCP servers lease IP based on MAC, so if that MAC is the same as your DSM MAC it will give conflicts.
> 
> Also you set `CONSOLE: "Y"` for some reason? I would not do that because it prevents the container from shutting down gracefully and corrupts the disk, its only for emergencies.


Oh, I thought i would connect to iptime's DHCP with that macvlan
and sorry for questioning a lot ;(

I changed the macvlan network to 
docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 --ip-range 192.168.1.0/24 -o parent=eth0 vdsm

and removed CONSOLE: "Y"
```
version: "3"
services:
    dsm:
        container_name: dsm
        image: vdsm/virtual-dsm:7.04
        environment:
            DISK_SIZE: "48G"
            RAM_SIZE: "2G"
            CPU_CORES: "2"
            URL: "https://global.synologydownload.com/download/DSM/release/7.2.1/69057-1/DSM_VirtualDSM_69057.pat"
            DHCP: "Y"
        devices:
            - /dev/kvm
            - /dev/vhost-net
        device_cgroup_rules:
            - 'c *:* rwm'
        cap_add:
            - NET_ADMIN
        ports:
            - 5000:5000
            - 5001:5001
            - 80:80
        volumes:
            - //c/docker_dsm:/storage
        networks:
            vdsm:
                ipv4_address: 192.168.1.120
        restart: always
        stop_grace_period: 2m
networks:
  vdsm:
    external: true
```
These options are not working because of download issue

I think this is pretty hard to set, so i need to go back to bridge mode :(
