### ISSUE TITLE
[Bug]: dsm pod unresponsive, unless DISK_FMT set to QCOW

### ISSUE THREAD

**Issue by SlavikCA** [vdsm/virtual-dsm#784]
### Operating system

Harvester 1.3.1 with Longhorn

### Description

I deploy virtual-dsm with Kubernetes manifest.
I added 2 discs:
- 380GB of SSD
- 2TB of HDD
- 
And found, that dsm is unresponsive unless I set  DISK_FMT to QCOW2.
If it's not set - I can't connect to dsm via the network.

Also, when I DISK_FMT is not set to QCOW2, the CPU usage is 100%.

Is it because dsm tried to write over 2TB upon start?

### Docker compose

```
apiVersion: v1
kind: Pod
metadata:
  name: dsm
  labels:
    name: dsm
  namespace: dsm
  annotations:
    # https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/how-to-use.md#launch-pod-with-json-annotation
    k8s.v1.cni.cncf.io/networks: '[ { "name": "untagged","namespace": "default","mac": "aa:fa:1b:fb:1a:54","interface": "net2" } ]'
spec:
  terminationGracePeriodSeconds: 120 # the Kubernetes default is 30 seconds and it may be not enough
  containers:
    - name: dsm
      image: vdsm/virtual-dsm
      resources:
        limits:
          devices.kubevirt.io/vhost-net: 1
          memory: "9Gi"
          cpu: "4"
        requests:
          cpu: 200m
          memory: "1Gi"
      securityContext:
        privileged: true
        capabilities:
          add: ["NET_ADMIN"]
      env:
        - name: RAM_SIZE
          value: 8G
        - name: CPU_CORES
          value: "4"
        - name: DISK_SIZE # shall be set to PVC size in Gi * 0.974
          value: "375G"
        - name: DISK2_SIZE
          value: "2000G"
        - name: DISK_FMT
          value: "qcow2" # qcow2 does not allocate the total disk size, but grows with the data
        - name: DHCP
          value: "Y"
        - name: VM_NET_DEV
          value: "net2"
      volumeMounts:
        - mountPath: /storage
          name: dsm-ssd
        - mountPath: /storage2
          name: dsm-hdd
        - mountPath: /dev/kvm
          name: dev-kvm
  volumes:
    - name: dsm-ssd
      persistentVolumeClaim:
        claimName: dsm-ssd-pvc
    - name: dsm-hdd
      persistentVolumeClaim:
        claimName: dsm-hdd-pvc
    - name: dev-kvm
      hostPath:
        path: /dev/kvm
```

### Docker log

[firstBootWithQCOW.txt](https://github.com/user-attachments/files/16199339/firstBootWithQCOW.txt)

[firstBootWithoutQCOW.txt](https://github.com/user-attachments/files/16199340/firstBootWithoutQCOW.txt)
