### ISSUE TITLE
Error on upgrade: "The available drive space of this system is unsufficient."

### ISSUE THREAD

**Issue by Grandma-Betty** [vdsm/virtual-dsm#814]
### Operating system

Debian 13

### Description

When trying to update the DSM version from version _7.2.2-72803_ to version _7.2.2-72806_ manually via uploading the according _.pat_-file, the following error message occurs:
_The available drive space of this system is unsufficient._

![Screenshot 2024-09-11 083630](https://github.com/user-attachments/assets/37ca8b85-d644-4086-b22a-ae6016602ee3)

When checking the filesystem it tells me this:

```
root@vdsm01:/var/log# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       2.0G  1.4G  450M  76% /
devtmpfs        5.9G     0  5.9G   0% /dev
tmpfs           5.9G  244K  5.9G   1% /dev/shm
tmpfs           5.9G   19M  5.9G   1% /run
tmpfs           5.9G     0  5.9G   0% /sys/fs/cgroup
tmpfs           5.9G   28M  5.9G   1% /tmp
tmpfs           1.2G     0  1.2G   0% /run/user/196791
/dev/loop0       27M  769K   24M   4% /tmp/SynologyAuthService
/dev/sdb1       123G   18G  106G  14% /volume1
```
So it seems the available space left on` /dev/sda1` is not enough for the system to upgrade. Is there any way I can expand the according partition? Maybe from the Docker host via _docker-compose_ or similiar?

Thank you in advance!

### Docker compose

```
networks:
  vdsm:
    driver: bridge
volumes:
  storage:
    driver: local
services:
#
# ****** vDSM ******
#
  vdsm:
    container_name: vdsm01
    image: vdsm/virtual-dsm:latest
    environment:
      DISK_SIZE: "128G"
      ALLOCATE: "N"
      DISK_FMT: "qcow2"
      RAM_SIZE: "12288M"
      CPU_CORES: "4"
      HOST_SERIAL: "****"
      GUEST_SERIAL: "****"
      VM_NET_MAC: "****"
    devices:
      - /dev/kvm
    volumes:
      - /home/supervisor/docker-volumes/vDSM01/storage:/storage
    networks:
      - vdsm
    cap_add:
      - NET_ADMIN
    ports:
      - "25:25"
      - "80:5000"
      - "110:110"
      - "143:143"
      - "443:5001"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "2525:2525"
      - "5000:5000"
      - "5001:5001"
      - "9022:22"
    restart: unless-stopped
    stop_grace_period: 60s
```

### Docker log

[logs.txt](https://github.com/user-attachments/files/16960039/logs.txt)
