### ISSUE TITLE
Stuck in Install Loop after DSM update

### ISSUE THREAD

**Issue by gameveloster** [vdsm/virtual-dsm#835]
### Operating system

Ubuntu 24.04

### Description

After updating 7.2.1 to 7.2.2 from inside the DSM webpage section `Control Panel > DSM Update` and restarting, we are greeted with an DSM downloadd screen

<img width="1130" alt="Screenshot 2024-10-25 at 10 15 46 AM" src="https://github.com/user-attachments/assets/bd3691cc-0be2-43e7-a1c8-b72a002db2ea">

1. Clicked the "Install" button
2. In the next screen, selected the "Retain system configuration" option and clicked "Next" button
3. In the next screen, selected the "Automatically download and install the latest DSM 7.2.2-72806 from Synology website" option and clicked "Next" button
4. Brought to the "Installing DSM" screen.

   <img width="1046" alt="Screenshot 2024-10-25 at 10 17 44 AM" src="https://github.com/user-attachments/assets/9c0fb2e5-d3e7-4ae5-bc8a-1a36151e2fec">

5. Brought to a countdown screen
   <img width="1058" alt="Screenshot 2024-10-25 at 10 18 29 AM" src="https://github.com/user-attachments/assets/16df861f-18e8-4b6f-bcb4-7bda85847c15">

  6. In a different browser tab, I kept trying to access `http://<virtusldsm_ip>:5000/` until the page finally loads when the container has started up.
  7. Am back to the "Welcome back" screen
     <img width="1130" alt="Screenshot 2024-10-25 at 10 15 46 AM" src="https://github.com/user-attachments/assets/bd3691cc-0be2-43e7-a1c8-b72a002db2ea">

### Docker compose

```yaml
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      DISK_SIZE: "5800G"
      RAM_SIZE: "2G"
      CPU_CORES: "2"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      - /mnt/sdb:/storage
    stop_grace_period: 2m
    privileged: true
    restart: unless-stopped
```

### Docker log

[docker_compose_logs_virtualdsm.txt](https://github.com/user-attachments/files/17523439/docker_compose_logs_virtualdsm.txt)
