### ISSUE TITLE
Getting "Cannot create macvtap interface" after a while

### ISSUE THREAD

**Issue by rummens** [vdsm/virtual-dsm#853]
### Operating system

RHEL 9

### Description

I am running the container on a Microshift/Kubernetes Single Node and it works perfectly. However after a while, I don't see any pattern as it ranges from 20-50m the Pod fails with the error below. My feeling is that its related so some action rather than a pure time based trigger. I did get a feeling once that either the Package Manager or HyperBackup could cause this as I saw some message around php being broken but this could be coincidence. 
After I delete the Pod and the Deployment recreates it, everything works super smooth again for a while.

I am using Multus inspired by this [post](https://github.com/vdsm/virtual-dsm/issues/687#issuecomment-2113954508) and the pod has escalated privileges as well as the NET_ADMIN privs as can be seen in the deployment config below. I did create a specific SCC to allow this, since OpenShift/Microshift needs additional approval. I also attached the _NetworkAttachmentDefinition_ I build to enable the macvlan.

Could you give me any pointers on how to debug this further? I do not want to exclude a Layer8 issue but I tried to configured everything as indicated in this repo or the various issues/docs I could find around it. 

Appreciate any help 
Thanks
Marcel

### Docker compose

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-virtual-dsm
  namespace: virtual-dsm
  labels:
    helm.sh/chart: virtual-dsm-0.1.0
    app.kubernetes.io/name: virtual-dsm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.20"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: virtual-dsm
      app.kubernetes.io/instance: release-name
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name":"macvlan-net","namespace":"default","interface":"macvlan-net"}]'
      labels:
        app.kubernetes.io/name: virtual-dsm
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-virtual-dsm
      securityContext:
        {}
      terminationGracePeriodSeconds: 120 # the Kubernetes default is 30 seconds and it may be not enough
      containers:
        - name: virtual-dsm
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
            privileged: true
          image: "vdsm/virtual-dsm:7.20"
          imagePullPolicy: IfNotPresent
          env:
            - name: RAM_SIZE
              value: "4G"
            - name: CPU_CORES
              value: "1"
            - name: DISK_SIZE
              value: "50G"
            - name: DHCP
              value: "Y"
            - name: VM_NET_DEV
              value: "macvlan-net"
            - name: DISK2_SIZE
              value: "3480G"
            - name: DISK3_SIZE
              value: "3480G"
          volumeMounts:
            - mountPath: /storage
              name: storage
            - mountPath: /dev/kvm
              name: dev-kvm
            - mountPath: /dev/net/tun
              name: dev-net-tun
            - mountPath: /storage2
              name: hdd-one
            - mountPath: /storage3
              name: hdd-two
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: release-name-virtual-dsm-pvc
        - name: dev-kvm
          hostPath:
            path: /dev/kvm
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        - name: hdd-one
          hostPath:
            path: /storage/disk1
        - name: hdd-two
          hostPath:
            path: /storage/disk2

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-net
  namespace: default
spec:
  config: '{
  "cniVersion": "0.3.1",
  "name": "macvlan-net",
  "type": "macvlan",
  "master": "enp0s20f0u7",
  "linkInContainer": false,
  "mode": "bridge",
  "ipam": {
    "type": "dhcp"
    }
}'

```

### Docker log

❯ Starting Virtual DSM for Docker v7.20...
❯ For support visit https://github.com/vdsm/virtual-dsm
❯ CPU: Intel Core TM i5 10500 CPU | RAM: 51/63 GB | DISK: 1672 GB (ext4) | HOST: 5.14.0-427.33.1.el9_4.x86_64...
RTNETLINK answers: File exists
❯ ERROR: Cannot create macvtap interface. Please make sure that the network type is 'macvlan' and not 'ipvlan',
❯ ERROR: that your kernel is recent (>4) and supports it, and that the container has the NET_ADMIN capability set.

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/1bd51b01-c3fc-4ef4-9485-84fefae315fa)
