### ISSUE TITLE
`tun` kmod is not available

### ISSUE THREAD

**Issue by LittleNewton** [vdsm/virtual-dsm#860]
### Operating system

Debian 12 bookworm

### Description

I found that all Active Backup for Business clients were offline and then I tried to restart virtual-dsm container. I realized restarting the container helped nothing, so I rebooted my Linux host. Unfortunately, this problem still happened.

I have tried:

- Restarting virtual-dsm container
- Rebooting my Debian 12 host
- Recreating a new container instance with a separate storage
- Invoking `modprobe tun` to enable kmod `tun`.

Now I have to run the container in the privileged mod and it is not common and secure.

### Docker compose

```yaml
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm:latest
    environment:
      - DISK_SIZE=16G
      - HOST_SERIAL=xxx
      - GUEST_SERIAL=xxx
      - VM_NET_MAC=xxx
    devices:
      - /dev/kvm
      - /dev/disk/by-id/wwn-XXX:/disk2
    cap_add:
      - NET_ADMIN
    volumes:
      - app_data/DSM/dsm:/storage
    restart: on-failure
    stop_grace_period: 1m
    networks:
      - reverse_proxy
    ports:
      - 5510:5510
      - 902:902
      - 445:445
      - 5985:5985
      - 5986:5986

networks:
  reverse_proxy:
    name: reverse_proxy
    external: true
```

### Docker log

```
❯ Starting Virtual DSM for Docker v7.20...
❯ For support visit https://github.com/vdsm/virtual-dsm
❯ CPU: Intel Xeon Gold 5117 CPU | RAM: 220/252 GB | DISK: 33247 GB (nfs) | HOST: 6.1.0-27-amd64...

❯ Install: Downloading installer...
curl: (22) The requested URL returned error: 416

     0K ........ ........ ........ ........  8% 33.1M 10s
 32768K ........ ........ ........ ........ 17% 38.6M 8s
 65536K ........ ........ ........ ........ 26% 39.3M 7s
 98304K ........ ........ ........ ........ 35% 39.4M 6s
131072K ........ ........ ........ ........ 44% 39.0M 5s
163840K ........ ........ ........ ........ 53% 38.5M 4s
196608K ........ ........ ........ ........ 61% 39.0M 4s
229376K ........ ........ ........ ........ 70% 38.5M 3s
262144K ........ ........ ........ ........ 79% 38.9M 2s
294912K ........ ........ ........ ........ 88% 38.8M 1s
327680K ........ ........ ........ ........ 97% 36.3M 0s
360448K ........ ..                        100% 38.7M=9.5s

❯ Install: Downloading DSM_VirtualDSM_72806.pat...

     0K ........ ........ ........ ........  9% 32.4M 10s
 32768K ........ ........ ........ ........ 18% 38.6M 8s
 65536K ........ ........ ........ ........ 27% 39.0M 7s
 98304K ........ ........ ........ ........ 37% 39.1M 6s
131072K ........ ........ ........ ........ 46% 38.9M 5s
163840K ........ ........ ........ ........ 55% 39.1M 4s
196608K ........ ........ ........ ........ 65% 39.1M 3s
229376K ........ ........ ........ ........ 74% 39.1M 2s
262144K ........ ........ ........ ........ 83% 39.0M 1s
294912K ........ ........ ........ ........ 92% 39.0M 1s
327680K ........ ........ ........         100% 39.4M=9.0s

❯ Install: Extracting downloaded image...
❯ Install: Preparing system partition...
❯ Install: Extracting system partition...
❯ Install: Installing system partition...
❯ Creating a 16G preallocated disk image in raw format...
open: Operation not permitted
❯ ERROR: The 'tun' kernel module is not available. Try this command: 'sudo modprobe tun' or run the container with 'privileged: true'.
❯ Warning: falling back to usermode networking! Performance will be bad and port forwarding will not work.
❯ Booting Virtual DSM using QEMU v9.1.0...
```

### Screenshots (optional)

<img width="1231" alt="image" src="https://github.com/user-attachments/assets/0f7c737d-088c-4c2e-a601-eee798b52a3d">
