### ISSUE TITLE
[Bug]:  ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28

### ISSUE THREAD

**Issue by geekyouth** [vdsm/virtual-dsm#866]
### Operating system

centos7

### Description

如下

### Docker compose

```
name: dsm-dev-macvlan
services:
  dsm:
    image: vdsm/virtual-dsm:7.21
    hostname: dsm
    container_name: dsm-dev-macvlan
    networks:
      macvlan1:
    environment:
      TZ: Asia/Shanghai
      DISK_FMT: "qcow2"
      DISK_SIZE: "50G" # 第一个名字是默认的，对应 /storage
      DISK2_SIZE: "50G"
      DISK3_SIZE: "50G"
      RAM_SIZE: "8G"
      CPU_CORES: "8"
      DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    volumes:
      # 多个磁盘
      - ./_docker-data/dsm-dev-macvlan/local/storage/:/storage/
      - /data/dsm-dev-macvlan/share2/:/storage2/
      - /data/dsm-dev-macvlan/share3/:/storage3/
    restart: unless-stopped
    stop_grace_period: 2m

networks:
  macvlan1:
    driver: macvlan
    attachable: true
    name: macvlan1
    driver_opts:
      parent: ${PARENT_NETCARD}
    ipam:
      config:
        - subnet: ${DEFAULT_GATEWAY_PREFIX}.0/24
          gateway: ${DEFAULT_GATEWAY_PREFIX}.1
          ip_range: ${DEFAULT_GATEWAY_PREFIX}.0/24

```

### Docker log

```

dsm-dev-macvlan exited with code 0
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10000 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10000 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10001 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10002 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10002 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10002 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10001 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10000 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10000 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10000 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10001 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10001 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10000 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10000 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10000 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10000 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10000 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.21...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 9/16 GB | DISK: 97 GB (xfs) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...

```

**Comment by geekyouth** [comment]
My host machine's network is normal and I can use wget to download the file from this URL. However, why can't the DSM container launched with the Docker Macvlan network use the local file specified by the URL parameter? This is very strange.

```yaml
name: dsm-dev-macvlan
services:
  dsm:
    cap_add:
      - NET_ADMIN
    container_name: dsm-dev-macvlan
    device_cgroup_rules:
      - c *:* rwm
    devices:
      - /dev/kvm
      - /dev/vhost-net
      - /dev/dri
    environment:
      CPU_CORES: "8"
      DHCP: "Y"
      DISK_FMT: qcow2
      DISK_SIZE: 50G
      DISK2_SIZE: 100G
      DISK3_SIZE: 100G
      GPU: "Y"
      RAM_SIZE: 8G
      TZ: Asia/Shanghai
      URL: DSM_VirtualDSM_72806.pat
    hostname: dsm
    image: vdsm/virtual-dsm:7.22
    networks:
      macvlan1: null
    restart: unless-stopped
    stop_grace_period: 2m0s
    volumes:
      - type: bind
        source: /data/dsm-dev-macvlan/storage/
        target: /storage
        bind:
          create_host_path: true
      - type: bind
        source: /data/dsm-dev-macvlan/share2/
        target: /storage2
        bind:
          create_host_path: true
      - type: bind
        source: /data/dsm-dev-macvlan/share3/
        target: /storage3
        bind:
          create_host_path: true
networks:
  macvlan1:
    name: macvlan1
    driver: macvlan
    driver_opts:
      parent: enp0s20u3u4
    ipam:
      config:
        - subnet: 192.168.8.0/24
          gateway: 192.168.8.1
          ip_range: 192.168.8.0/24
    attachable: true

```

```
[root@g480 storage]# ll
总用量 345M
drwxr-xr-x 3 root root 4.0K 1月  18 16:30 .
drwxr-xr-x 5 root root 4.0K 1月  18 16:14 ..
-rw-r--r-- 1 root root 345M 1月  18 16:00 DSM_VirtualDSM_72806.pat
drwxr-xr-x 2 root root 4.0K 1月  18 16:30 tmp
[root@g480 storage]#

```

error log
```
dsm-dev-macvlan  | ❯ Install: Downloading installer...
dsm-dev-macvlan  | curl: (28) Resolving timed out after 10000 milliseconds
dsm-dev-macvlan  | ❯ ERROR: Failed to download https://cndl.synology.cn/download/DSM/release/7.0.1/42218/DSM_VirtualDSM_42218.pat , reason: 28
dsm-dev-macvlan  | ❯ Starting Virtual DSM for Docker v7.22...
dsm-dev-macvlan  | ❯ For support visit https://github.com/vdsm/virtual-dsm
dsm-dev-macvlan  | ❯ CPU: Intel Core i5 3230M | RAM: 10/16 GB | DISK: 435 GB (ext4) | KERNEL: 3.10.0-1160.80.1.el7.x86_64...
dsm-dev-macvlan  |
dsm-dev-macvlan  | ❯ Install: Downloading installer...
```

**Comment by geekyouth** [comment]
```
name: dsm-dev
services:
  dsm:
    cap_add:
      - NET_ADMIN
    container_name: dsm-dev
    device_cgroup_rules:
      - c *:* rwm
    devices:
      - /dev/kvm
      - /dev/vhost-net
      - /dev/dri
    environment:
      ALLOCATE: "N"
      CPU_CORES: "8"
      DHCP: "Y"
      DISK_FMT: qcow2
      DISK_SIZE: 1T
      DISK2_SIZE: 50T
      DISK3_SIZE: 50T
      GPU: "Y"
      RAM_SIZE: 8G
      TZ: Asia/Shanghai
      URL: DSM_VirtualDSM_72806.pat
    hostname: dsm
    image: vdsm/virtual-dsm:7.22
    networks:
      fullstack: null
    ports:
      - mode: ingress
        target: 5000
        published: "5000"
        protocol: tcp
    restart: unless-stopped
    stop_grace_period: 2m0s
    volumes:
      - type: bind
        source: /data/dsm-dev/storage/
        target: /storage
        bind:
          create_host_path: true
      - type: bind
        source: /data/dsm-dev/share2/
        target: /storage2
        bind:
          create_host_path: true
      - type: bind
        source: /data/dsm-dev/share3/
        target: /storage3
        bind:
          create_host_path: true
networks:
  fullstack:
    name: fullstack
    ipam:
      config:
        - subnet: 172.16.1.0/24

```

```
[root@g480 storage]# cd /data/dsm-dev/storage/
[root@g480 storage]# ll
总用量 345M
drwxr-xr-x 2 root root 4.0K 1月  18 16:45 .
drwxr-xr-x 3 root root 4.0K 1月  18 16:45 ..
-rw-r--r-- 1 root root 345M 1月  18 16:45 DSM_VirtualDSM_72806.pat

```

I'm sure the URL parameters are not working, even though I'm using the Docker bridge network.

![Image](https://github.com/user-attachments/assets/de99ff9c-a81e-4430-a99b-52dc3cf98bb4)
