### ISSUE TITLE
[Question]: Multiple disks. How do I assign the disk type to multiple disks?

### ISSUE THREAD

**Issue by MarcS1975** [vdsm/virtual-dsm#868]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/vdsm/virtual-dsm/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

First of all, does the environment variable name count in defining disks or is it just the order of lising inside the compose file that counts? So will DISK**X**_SIZE always correspond to /storage**X** (see below) ? And If I have multiple disks, how do I specify which disk is a **growing** `qcow2` disk and which is a static disk?

``` 

environment:
  DISK_FMT: "qcow2"
  DISK2_SIZE: "32G"
  DISK3_SIZE: "64G"
volumes:
  - /home/example:/storage2
  - /mnt/data/example:/storage3
```
