### ISSUE TITLE
[Bug]: network setup locks the host

### ISSUE THREAD

**Issue by MarcS1975** [vdsm/virtual-dsm#883]
### Operating system

Debian 12 bookworm

### Description

Setting up the vDSM as per the documentation with a docker network locks up th entire host and no access is possible unless restart
Router DHCP is limited for range 192.168.1.1 - 192.168.1.199
Network is created like this:
```
docker network create -d macvlan \
    --subnet=192.168.1.0/24 \
    --gateway=192.168.1.1 \
    --ip-range=192.168.1.200/29 \
    -o parent=eth0 vdsm
```

### Docker compose

```
services:
  dsm:
    container_name: dsm
    networks:
       vdsm:
         ipv4_address: 192.168.1.200
    image: vdsm/virtual-dsm
    environment:
      DISK_SIZE: "20G"
      DISK_FMT: "qcow2"
     RAM_SIZE: "3G"
     CPU_CORES: "2"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    #ports:
    #  - 5000:5000
    volumes:
      - /srv/dockerapps/vdsm:/storage
    stop_grace_period: 2m
networks:
  vdsm:
    external: true
```

### Docker log

n/a
