### ISSUE TITLE
vDSM not booting, EXT4-fs errors

### ISSUE THREAD

**Issue by SamKr** [vdsm/virtual-dsm#895]
### Operating system

Ubuntu 24.04.1

### Description

I have a vDSM instance which has been running perfectly for weeks. It has 4 disks attached; 1 for vDSM, and 3 for storage. All virtual. However, since yesterday, I'm unable to contact the portal and nothing is working anymore. It appears as though SDA1 has become corrupt. 

Do you have a recommended way of perhaps running fsck, or another method to try and repair it? 

The logs are showing tons of these messages:

```sh
dsm  | [  131.256255] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394634: comm synow3tool: bad extra_isize (12984 != 256)
dsm  | [  131.338806] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394634: comm synow3tool: bad extra_isize (12984 != 256)
dsm  | [  131.696809] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394634: comm nginx: bad extra_isize (12984 != 256)
dsm  | [  131.772921] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394634: comm nginx: bad extra_isize (12984 != 256)
dsm  | [  131.811559] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394634: comm nginx: bad extra_isize (12984 != 256)
dsm  | [  131.876630] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394634: comm nginx: bad extra_isize (12984 != 256)
dsm  | [  131.908941] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394634: comm nginx: bad extra_isize (12984 != 256)
dsm  | [  131.956173] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394634: comm nginx: bad extra_isize (12984 != 256)
dsm  | [  132.087104] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394634: comm nginx: bad extra_isize (12984 != 256)
dsm  | [  132.121354] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394634: comm nginx: bad extra_isize (12984 != 256)

dsm  | [  172.895840] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
dsm  | [  172.927489] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
dsm  | [  172.944106] EXT4-fs error (device sda1): ext4_xattr_set_entry:684: inode #394637: comm syslog-ng: corrupted xattr entries
dsm  | [  182.894458] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
dsm  | [  182.917397] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
dsm  | [  182.966767] EXT4-fs error (device sda1): ext4_xattr_set_entry:684: inode #394637: comm syslog-ng: corrupted xattr entries

dsm  | [ 1373.442134] EXT4-fs error (device sda1): ext4_xattr_set_entry:684: inode #394637: comm syslog-ng: corrupted xattr entries
dsm  | [ 1383.382332] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
dsm  | [ 1383.451733] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
dsm  | [ 1383.475481] EXT4-fs error (device sda1): ext4_xattr_set_entry:684: inode #394637: comm syslog-ng: corrupted xattr entries
dsm  | [ 1393.383526] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
dsm  | [ 1393.405873] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
dsm  | [ 1393.422090] EXT4-fs error (device sda1): ext4_xattr_set_entry:684: inode #394637: comm syslog-ng: corrupted xattr entries
dsm  | [ 1403.384617] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
dsm  | [ 1403.411267] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
dsm  | [ 1403.426186] EXT4-fs error (device sda1): ext4_xattr_set_entry:684: inode #394637: comm syslog-ng: corrupted xattr entries
dsm  | [ 1413.386274] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
dsm  | [ 1413.402008] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394638: comm syslog-ng: bad extra_isize (58997 != 256)
```

Some other log entries that might be relevant:

```sh
dsm  | ============bootup-smallupdate
dsm  | Wait 2 seconds for synology manufactory device
dsm  | Mon Feb 17 14:10:23 UTC 2025
dsm  | /dev/sda1 /tmpRoot ext4 rw,noatime,data=ordered 0 0
dsm  | none /sys/kernel/debug debugfs rw,relatime 0 0
dsm  | root: Start backing up logs in junior mode
dsm  | [   30.982626] EXT4-fs (sda1): couldn't mount as ext3 due to feature incompatibilities
dsm  | [   31.006530] EXT4-fs (sda1): warning: mounting fs with errors, running e2fsck is recommended
dsm  | [   31.038716] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
dsm  | umount: /etc/mtab: No such file or directory
```

```sh
dsm  | [  OK  ] Started udev Coldplug all Devices.
dsm  | [   35.369853] i40evf: Intel(R) 40-10 Gigabit Virtual Function Network Driver - version 3.6.15
dsm  | [   35.382586] Copyright(c) 2013 - 2018 Intel Corporation.
dsm  | [FAILED] Failed to start Mount usb fs.
dsm  | See "systemctl status syno-mount-usbfs.service" for details.
dsm  | [   35.406802] igbvf: Intel(R) Gigabit Virtual Function Driver - 2.3.8.2
dsm  | [   35.415917] igbvf: Copyright (c) 1999-2015 Intel Corporation.
dsm  | [  OK  ] Started D-Bus System Message Bus.
dsm  | [   35.445481] ixgbevf: Intel(R) 10GbE PCI Express Virtual Function Driver - version 4.5.3
dsm  | [   35.461413] Copyright(c) 1999 - 2019 Intel Corporation.
dsm  | [   35.464619] EXT4-fs error (device sda1): __ext4_iget:4365: inode #394635: comm systemd-tmpfile: bad extra_isize (63473 != 256)
dsm  | [  OK  ] Started Synology Network Daemon.
dsm  |          Starting Wait for synonetd ready...
dsm  | [FAILED] Failed to start Create Volatile Files and Directories.
dsm  | See "systemctl status systemd-tmpfiles-setup.service" for details.
dsm  | [DEPEND] Dependency failed for Create SDK locks directory.
dsm  | [DEPEND] Dependency failed for Check /etc/synoinfo.conf.
dsm  |          Starting synodsmnotify...
dsm  |          Starting Check Synology user info consistency...
dsm  |          Starting Check Synology group info consistency...
dsm  |          Starting Synology Database Update...
dsm  | [  OK  ] Started synodsmnotify.
dsm  | [  OK  ] Started Load Kernel Modules.
dsm  |          Starting Adjust NIC sequence...
dsm  |          Starting Apply default and user cus... sysctl.conf kernel variable....
dsm  |          Mounting Configuration File System...
dsm  |          Starting Load Fan Modules in Kernel Project...
dsm  |          Starting Load Kernel Modules in Kernel Project...
dsm  | [  OK  ] Mounted Configuration File System.
dsm  | [  OK  ] Started Wait for synonetd ready.
dsm  | [[   35.754637] usbcore: registered new interface driver usblp
dsm  | FAILED] Failed to start Adjust NIC sequence.
dsm  | See "systemctl status SynoInitEth.service" for details.
dsm  | [  OK  ] Started Synology Database Update.
dsm  | [  OK [   35.810243] usbcore: registered new interface driver usbhid
```

```sh
dsm  | [  OK  ] Started System Logger Daemon.
dsm  |          Starting synodrnode...
dsm  | [DEPEND] Dependency failed for rebuild local user and group db.
dsm  | [  OK  ] Reached target Synology root filesystem (rw) ready.
```

### Docker compose

```yaml
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    restart: unless-stopped
    environment:
      DISK_SIZE: "50G"
      DISK2_SIZE: "10T"
      DISK3_SIZE: "10T"
      DISK4_SIZE: "10T"
      RAM_SIZE: "2G"
      CPU_CORES: "2"
      MAC: "XX:XX:XX:XX:XX:XX"
      GUEST_SERIAL: "-------------------"
      HOST_SERIAL: "-------------------"
      HOST_MAC: "XX:XX:XX:XX:XX:XX"
      HOST_MODEL: "DS3622xs+"
      DISK_FMT: "qcow2"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
      - 6080:6080
      - 6443:6443
      - 7080:7080
      - 7443:7443
      - 5510:5510
    volumes:
      - /var/vdsm:/storage
      - /storage/disk2/vdsm/storage:/storage2
      - /storage/disk3/vdsm/storage:/storage3
      - /storage/disk4/vdsm/storage:/storage4
    stop_grace_period: 2m
```

### Docker log

Uploaded as a file due to its length:

[vdsm_docker_log.txt](https://github.com/user-attachments/files/18827295/vdsm_docker_log.txt)
