### ISSUE TITLE
Cannot start Openproject docker compose application inside VDSM

### ISSUE THREAD

**Issue by awa5114** [vdsm/virtual-dsm#896]
### Operating system

Windows 11

### Description

I'm trying to start an OpenProject compose application inside the Virtual DSM for testing purposes. We have a real server at our company and I would rather test things in a sandbox before implementing them on the real device. Once the Virtual DSM is successfully created, I go to `localhost:5000` on my browser and do the following:

- Install Container Manager
- Install and run Git Server
- Enable SSH and set it to port 22

This all works fine, as you would expect on a real DSM.

Then, from the host machine I try to SSH into the DSM as follows:

```
ssh <username>@localhost
```

This also works, and I navigate to `/volume1/docker`, and run the commands recommended by the OpenProject docker compose install [page](https://www.openproject.org/docs/installation-and-operations/installation/docker-compose/#quick-start), namely

```
ssh@localhost> git clone https://github.com/opf/openproject-deploy --depth=1 --branch=stable/15 openproject
ssh@localhost> cp .env.example .env
```

I perform no further changes, and launch the OpenProject compose application from within the virtual DSM:

```
ssh@localhost> sudo docker-compose up
```

It attempts to start up the application, but after a while, everything hangs, and I am no longer able to navigate to the Synology UI from my browser (`localhost:5000`), unable to SSH into the virtual DSM and the OpenProject app is not up and running on `localhost:8080`.

Restarting virtual DSM from the host machine using `docker compose stop` followed by `docker compose start` also doesn't properly anymore, which is quite frustrating since I have to completely tear down the virtual DSM using `docker compose down` followed by `docker compose up`, which takes really long.

### Docker compose

Using a slightly modified compose file than the one in the README 

```
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      DISK_SIZE: "16G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000 # Synology UI
      - 8080:8080 # openproject
      - 22:22 # SSH
    volumes:
      - C:/Users/amine/Desktop/TEMP/dsm-docker/v722/storage:/storage
    restart: always
    stop_grace_period: 2m
```

I start the above using `docker compose up`

### Docker log

The last few lines from my SSH session are as follows, please note this is from the docker log *inside* the virtual DSM and not from the host machine:

```
 => [3/3] RUN sed 's|${APP_HOST}|'"web"'|g' /etc/caddy/Caddyfile.template > /etc/cad  1.4s
 => exporting to image                                                                0.8s
 => => exporting layers                                                               0.7s
 => => writing image sha256:b8f428ac01bbbbf2b781f5dc4bcc21eca40c00c53633089c9722509f  0.0s
 => => naming to docker.io/openproject/proxy  
```

The last few lines from the docker logs on the host machine are as follows:

```
dsm  | [  700.884821] docker0: port 1(docker28ac40d) entered forwarding state
dsm  | [  700.890601] docker0: port 1(docker28ac40d) entered forwarding state
dsm  | [  700.897904] IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready
dsm  | [  701.036140] docker0: port 1(docker28ac40d) entered disabled state
dsm  | [  701.041935] docker9dc5b40: renamed from eth0
dsm  | [  701.152377] docker0: port 1(docker28ac40d) entered disabled state
dsm  | [  701.157947] device docker28ac40d left promiscuous mode
dsm  | [  701.162693] audit: type=1700 audit(1740244487.251:35): dev=docker28ac40d prom=0 old_prom=256 auid=4294967295 uid=0 gid=0 ses=4294967295
dsm  | [  701.173069] docker0: port 1(docker28ac40d) entered disabled state
```
