### ISSUE TITLE
virtual-dsm docker compose on ubuntu, cannot merge docker volumes as volume group inside DSM

### ISSUE THREAD

**Issue by txemi** [vdsm/virtual-dsm#985]
### Operating system

ubuntu 24.04

### Description

I am using virtual-dsm in order to use synology photos, my physical synology is very slow for this (there are lots of photos) and I wanted to try same software in more powerful hardware in order to know if more hardware would be the solution. 

I am trying some things and as  I need to add and remove storage from DSM in order to restore synology_photos backup (hyper backup), and later remove storage I do not need. But I think virtual DSM does not allow to combine volumes passed from docker;  I see that a new docker volume becomes a dsm volume as soon as I attach a new docker volume, not having opportunity to manage a group of disks and add or remove disks from dsm groups as usually done with physical synolgy nas. No HDD o r SDD information can be seen in storage manager.

I do not want to make a single huge volume because I presume i will not be able to shrink in future and I  need lot of space for restorage and reduce size later as I expected if I merged dsm disks (docker volumes) I could remove some later as in RAID SHR.

If this cannot be done in virtual-dsm I would thank confirmation, as I have spent a lot of time trying to work with virtual dsm as I did with my previous one and perhaps I am trying to do something that is impossible.

Thanks!

### Docker compose

```yaml
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      DISK_SIZE: "16G"
      DISK2_SIZE: "950G"
      DISK_FMT: "qcow2"
      # DISK_TYPE: "sata" # Revert back to default (scsi)
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      - ./dsm:/storage
      - ./dsm2:/storage2 # Add mapping for the second disk
    restart: always
    stop_grace_period: 2m
```

### Docker log

```shell
docker logs dsm
❯ Starting Virtual DSM for Docker v7.35...
❯ For support visit https://github.com/vdsm/virtual-dsm
❯ CPU: Intel Core i5 13500 | RAM: 2/8 GB | DISK: 943 GB (ext4) | KERNEL: 6.11.0-24...

❯ Nested KVM virtualization detected..
❯ Booting Virtual DSM using QEMU v9.2.92...
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000007H:EDX.invtsc [bit 8]
```
