### ISSUE TITLE
Slow HDD performance

### ISSUE THREAD

**Issue by timo1235** [vdsm/virtual-dsm#991]
### Operating system

unraid 7.1.2

### Description

Hello, im experiencing bad HDD performance when using vdsm. I have the main volume stored on SSD and want a second volume to use my unraid array(HDD) to store larger amounts of data.

The throughput always drops after some seconds. See the screenshot here:
![Image](https://github.com/user-attachments/assets/5e98d2ce-d503-4863-9bad-2c6efe460796)

I testet already:
- no change between using qcow2 or not
- tried different protocols: smb, nfs, file station via WebUI
- tried to install and pass a dedicated sata drive -> this speeds up to ~30MB/s
![Image](https://github.com/user-attachments/assets/4d76c3a4-f95d-4bee-9095-f738f7cb306b)
- when I copy to SSD, its always at full network capacity  ~90-100MB/s
- no difference if I use data integrity check for the shared folder in synology

On my host I can easy copy files with 200MB/s, so I guess its no limitation of the HDDs itself. 

My question would be, can I do something to make it more performant or is the solution to use SSDs for storage instead of HDDs? Couldnt find anything on the readme or in all the issues here.

Here is a complete log, since the characters are limited here.
[log2.txt](https://github.com/user-attachments/files/20604790/log2.txt)

### Docker compose

```yaml
services:
  vdsm:
    container_name: vdsm
    image: vdsm/virtual-dsm
    environment:
      GPU: "Y"
      DISK_SIZE: "200G"
      RAM_SIZE: "4G"
      CPU_CORES: "12"
      HOST_SERIAL: XXX
      HOST_MODEL: DS920+
      HOST_MAC: XX
      MAC: XX
      GUEST_SERIAL: XXX
    networks:
      br0:
        ipv4_address: 192.168.1.5
    devices:
      - /dev/sdb:/disk2
      - /dev/dri
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      - ./dsm:/storage
    restart: unless-stopped
    stop_grace_period: 2m
    
networks: 
  br0:
    external: true
```

### Docker log

```shell
see attached file
```
