### ISSUE TITLE
Display external hard drives on VDSM

### ISSUE THREAD

**Issue by GBInformatics** [vdsm/virtual-dsm#993]
### Operating system

Debian 12

### Description

Hello, I don't have all the knowledge so I'd like to ask you if it's possible to do what I want to do.

I want to reassemble 2 external hard drives by plugging them into the computer's usb ports.

I can see them and access them on the icons, but nothing on vdsm.
Can you please help me?

### Docker compose

```yaml
services:
  dsm:
    container_name: Virtual_DiskStationManager
    image: vdsm/virtual-dsm:latest
    environment:
      DISK_SIZE: "100G"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      TITLE: Virtual_DiskStationManager
    stop_grace_period: 2m
    devices:    
      - /dev/kvm
      - /dev/sdb:/dev/sdb  # Périphérique complet        
      - /dev/sdc:/dev/sdc  # Périphérique complet          
      - /dev/sdd:/dev/sdd  # Périphérique complet  
      - /dev/sde:/dev/sde  # Périphérique complet  
      - /dev/sdf:/dev/sdf  # Périphérique complet  
      - /dev/sdg:/dev/sdg  # Périphérique complet
      # Périphériques USB dynamiques
      - /dev/bus/usb:/dev/bus/usb
    privileged: true  # Nécessaire pour l'accès complet aux périphériques
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    volumes:
      - /home/docker/virtualdiskstationmanager:/storage/virtualdiskstationmanager
      - /mnt/usb-disk:/data/usb-disk    # Ajout pour le disque USB externe
      - /dev:/dev:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /sys/bus/usb:/sys/bus/usb:ro
      - /run/udev:/run/udev:ro
      - /mnt/usb:/usb-data
      - /mnt/usb1:/usb-data1
      - /mnt/usb2:/usb-data2
      - /mnt/usb3:/usb-data3
      - /mnt/usb4:/usb-data4
      - /mnt/usb5:/usb-data5
      - /mnt/usb6:/usb-data6
    restart: on-failure:5
    ports:
      - 10040:5000  
      - 10050:5001
    networks:
      Virtual_DiskStationManager:
        ipv4_address: 172.168.2.1
    
networks:
  Virtual_DiskStationManager:    
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.2.0/24
          gateway: 172.168.2.254
```

### Docker log

```shell
N/A
```
